import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.scss'
import { useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const getGithubUser = () => {
    const fetchData = fetch(`https://api.github.com/users`)
    fetchData.then(res => res.json())
    .then(data => console.log("data== ", data))
  }

  useEffect(() => {getGithubUser()}, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.home_page}>
       <h1>Github Users Rocket Reviews</h1>
       <main className={styles.home_main}></main>
        <section></section>
        <section></section>
      </main>
    </>
  )
}
