import Head from 'next/head'
import styles from '@/styles/Home.module.scss'
import { useContext, useEffect, useState } from 'react'
import { ReviewCard, ReviewForm } from '@/components'
import { AppContext } from '@/context/AppContext'
import { IRocketReviewItem } from '@/utils'


export default function Home() {
  const {reviewArray} = useContext(AppContext)
  const [singleRocket, setSingleRocket] = useState<IRocketReviewItem | undefined>()
  const [editCard, setEditCard] = useState(false) 


  return (
    <>
      <Head>
        <title>Sora Union Rocket App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.home_page}>
       <h1>Github Users Rocket Reviews</h1>
       <main className={styles.home_main}>
          {Boolean(reviewArray.length) && <section className={styles.home_section}>
            <h4>List of Rockets</h4>
            {reviewArray.map((item, i: number) => (
              <ReviewCard 
                key={item.id}
                username={item.username} 
                description={item.description}
                avatar_url={item.avatar_url}
                id={item.id}
                title={item.title}
                rocketName={item.rocketName}
                onClick={() => {
                  setSingleRocket(item)
                  setEditCard(true)
                }}
              />
            ))}
          </section>}
          <section className={styles.home_section}>
            <h4>{editCard ? "Edit Rocket" : "Create Rocket"}</h4>
            <ReviewForm editObj={singleRocket} setSingleRocket={setSingleRocket} editCard={editCard} setEdit={setEditCard} />
          </section>
        </main>
      </main>
    </>
  )
}
